name: chatbot_dialogflow
description: A new Flutter project.


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3
  flutter_dialogflow: ^0.1.3
  bubble: ^1.1.9+1
  firebase_auth: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - assets/google-services.json
    - assets/bot.png
    - assets/Bebo.png


